language: python
cache: pip
python:
  - "3.6"
  - "3.7"
  - "3.7-dev"
  - "nightly"
dist: xenial

jobs:
before_install:
  - pip install -U pip flit codecov
install:
  - flit install --deps develop
script: pytest .tests/
after_success: codecov
