[build-system]
requires = ["flit"]
build-backend = "flit.buildapi"

[tool.flit.metadata]
module = "topojson"
author = "Mattijn van Hoek"
author-email = "mattijn@gmail.com"
home-page = "https://github.com/mattijn/topojson"
requires = ["numpy", "shapely"]
keywords = "topojson python github topology geojson"
description-file = "README.md"
classifiers = ["License :: OSI Approved :: BSD License"]

[tool.flit.metadata.requires-extra]
<<<<<<< HEAD
dev = [
    "shapely >=1.7a2",
    "geojson", 
    "simplification", 
    "pyshp", 
    "fiona >=1.8.6", 
    "geopandas", 
    "altair", 
    "ipywidgets",
    "pytest=^5.1.1"
]
=======
dev = ["fiona", "geopandas", "altair", "ipywidgets", "pytest=^5.1.1"]
>>>>>>> 0f4e4fef1c138bdbd4bf73e88b48f8443bb7289b

